name: 'Kubernetes Test'
description: 'Deploy to Kind cluster, run integration tests, and collect diagnostics'

inputs:
  github-token:
    description: 'GitHub token for Docker registry authentication'
    required: true

runs:
  using: composite
  steps:
    - name: Install K8s tools
      shell: bash
      run: sudo ${{ github.action_path }}/../scripts/install-k8s-tools.sh

    - name: Validate K8S manifests
      shell: bash
      run: ./test/validate-k8s-yaml.sh

    - name: Create Kind Cluster
      shell: bash
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_DOCKER_SERVER: ghcr.io/${{ github.repository_owner }}
      run: ${{ github.action_path }}/../scripts/create-kind-cluster.sh

    - name: Test Kind installation
      shell: bash
      run: ./test/test-kind-cluster.sh

    - name: Install infrastructure services
      shell: bash
      run: ./manage/install-infrastructure-services.sh

    - name: Test Kafka
      shell: bash
      run: ./test/test-kafka.sh

    - name: Test Get JWT
      shell: bash
      run: ./test/get-jwt.sh

    - name: Test customer service
      shell: bash
      run: ./test/test-all-services.sh

    - name: Save pod logs
      if: always()
      shell: bash
      run: ${{ github.action_path }}/../scripts/dump-k8s.sh

    - name: Get container logs
      if: always()
      shell: bash
      run: ${{ github.action_path }}/../scripts/print-container-logs.sh

    - name: Save test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          **/build/reports
          **/build/test-results

    - name: Save container logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: container-logs
        path: ~/container-logs

    - name: Undeploy services
      if: always()
      shell: bash
      run: ./manage/undeploy-services.sh

    - name: Delete Kind Cluster
      if: always()
      shell: bash
      run: ${{ github.action_path }}/../scripts/delete-kind-cluster.sh
